theme: jekyll-theme-time-machine
title: Diana Bray for U.S. Senate Blog
description: My name is William Kelley. I am a Junior Computer Science major at Middlebury College, currently iterning for Diana Bray’s 2020 U.S. Senatte Race in Colorado. In this blog, I will detail my experience working on the campaign and living in Denver for the month of January.
